---
title: "Association Rule"
output: html_document
date: "Updated: `r format(Sys.time(), '%d %B, %Y')`"
---

## Read transaction data

### Groceries

```{r}
suppressMessages(library(arules))
data(Groceries)
Groceries

inspect(Groceries[1:3])
```

### simple basket without any sequence

```{r}
my_data = paste("1,2","1","2,3", sep="\n");
write(my_data, file = "my_basket");
trans = read.transactions("my_basket", format = "basket", sep=",");
inspect(trans);
```

###  'single' format

```r
item_df <- df[, c("windowID", "X733specificprob")]

item_df[1:4,]
              windowID                             X733specificprob
46446 AC11205_01/09/2017 multi_site_outage_hua_power_problem_(m.3100)
46447 AC11205_01/09/2017       site_outage_hua_power_problem_(m.3100)
46416 AC11219_03/09/2017       site_outage_hua_power_problem_(m.3100)
44737 AC11586_02/09/2017       site_outage_hua_power_problem_(m.3100)


write.csv(item_df, file = "myTemp.csv", row.names = F, quote = F)
# column 1 contains the transaction ID and column 2 contains one item
trans = read.transactions("myTemp.csv", format = "single", sep=",", cols = c(1,2), skip = 1)
length(trans)==length(unique(item_df$windowID))
cat("number of trans: ", length(trans), "\n")
inspect(trans[1:10]

[1]  {multi_site_outage_hua_power_problem_(m.3100),                                      
      site_outage_hua_power_problem_(m.3100)}                         AC11205_01/09/2017   
[2]  {site_outage_hua_power_problem_(m.3100)}                         AC11219_03/09/2017   
[3]  {site_outage_hua_power_problem_(m.3100)}                         AC11586_02/09/2017   
[4]  {cabinet_main_failure_external_power_supply_failure_(gsm_12.11)} BAG11_01/09/2017
[5]  {cabinet_main_failure_external_power_supply_failure_(gsm_12.11)} BAG11_02/09/2017
```

### basket data

```{r}
library(arulesSequences, quietly=T )

# sequence dataset
# {a}, {b}
# {a}, {c}
# {a}, {a,b}

# build sequence dataset as a data frame
df <- data.frame(sequenceID = c(1,1,2,2,3,3),
                 eventID = c(1,2,1,2,1,2),
                 Size = c(1,1,1,1,2,2),
                 items = c("a","b","a","c","a", "a,b")
                 )

df <- data.frame(lapply(df, as.factor))

write.table(df, file="myTemp.csv", sep = ",", row.names = F, col.names = F, quote=F)

# "sequenceID" (sequence or customer identifier) and "eventID" (time or event identifier)
t <- read_baskets("myTemp.csv", sep=",", info = c("sequenceID","eventID" , "SIZE"))

# convert transaction as data frame
as(t, "data.frame")

inspect(t)

# get transactionInfo
transactionInfo(t)
```

## arules apriori

http://www.salemmarafi.com/code/market-basket-analysis-with-r/


```{r}
library(arules, quietly = T)

rules <- apriori(t, parameter=list(support=0.1, confidence=0.5))

inspect(rules)
##     lhs    rhs support   confidence lift
## [1] {}  => {a} 0.6666667 0.6666667  1.00
## [2] {b} => {a} 0.1666667 0.5000000  0.75


# sort rules
inspect(head(sort(rules, by="lift"), 10))

as(rules, "data.frame")
```

rule to data frame with lhs an rhs in different column
```r
source_url('https://raw.githubusercontent.com/brooksandrew/Rsenal/master/R/rules2df.R')
```

Visualization
```{r}
library(arulesViz)
plot(rules, method="graph"
     #, interactive=TRUE
     , shading=NA)
```

http://mhahsler.github.io/arulesViz/reference/plot.html

## arulesSequences cspade

Frequent sequence mining

```{r}

# Mining Frequent Sequence
# set the support parameter to 0.3, and also have instructed the algorithm to show a verbose output.
s1 <- cspade(t, parameter=list(support = 0.3), control=list(verbose = TRUE))

as(s1, "data.frame")

#  default value for confidence of 0.8
s2 <- ruleInduction(s1, confidence = 0)

as(s2, "data.frame")

```


built in data from arulesSequences package

```r
library(arulesSequences)

# -- sample data
# $ cat /usr/local/lib/R/site-library/arulesSequences/misc/zaki.txt
# 1 10 2 C D
# 1 15 3 A B C
# 1 20 3 A B F
# 1 25 4 A C D F


# convert data to transactions
# A sequence α is an ordered list of events. An event is a non-empty unordered set of items. 
t <- read_baskets(con=system.file("misc", "zaki.txt", package="arulesSequences"),
		  info = c("sequenceID","eventID","SIZE"))
	
# show transaction
inspect(t)
##        items sequenceID eventID SIZE
## 1      {C,D}          1      10    2
## 2    {A,B,C}          1      15    3
## 3    {A,B,F}          1      20    3
## 4  {A,C,D,F}          1      25    4
## 5    {A,B,F}          2      15    3

```


