---
title: "Dimension reduction"
output: html_document
date: "Updated: `r format(Sys.time(), '%d %B, %Y')`"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# PCA
*prcomp* or *princomp*

prcomp is preferred according to:
https://stats.stackexchange.com/questions/20101/what-is-the-difference-between-r-functions-prcomp-and-princomp

```{r}
#------------ generate data ----------
N <- 500
factor1 <- rnorm(N)
factor2 <- rnorm(N) 
x1 <- rnorm(N) + factor1
x2 <- rnorm(N) + factor1
x3 <- rnorm(N) + factor2 
x4 <- rnorm(N) + factor2
mydat <- data.frame(x1,x2,x3,x4)

# ---------- use prcomp ------------
pca <- prcomp(mydat)
names(pca)
plot(pca) # plot the eigenvalues
biplot(pca) # A two dimensional plot

# --------- use princomp ------------

pca2 <- princomp(mydat)
pca2 <- princomp(~ x1 + x2 + x3 + x4, data = mydat) # princomp with a formula syntax
biplot(pca2)


```

# SVD

---
title: "SVD"
output: html_document
---


```{r}
# sequence 1 to 240 with gap 2
dat <- seq(1,120, 2)
# dat

X <- matrix(dat,ncol=6)
X

s <- svd(X)

# diag() : constructs a diagonal matrix
# contract a diagonal matrix from a vector s$d
D <- diag(s$d)

# X = U D V'
# where U and V are orthogonal, V' means V transposed, and D is a diagonal matrix with the singular values D[i,i]. 
s$u %*% D %*% t(s$v) 

```

## Golf example

http://datascientistinsights.com/2013/02/17/single-value-decomposition-a-golfers-tutotial/

```{r, echo=FALSE}
# build the matrix
scores <- c(4,4,3,4,4,3,4,2,5,4,5,3,5,4,5,4,4,5,5,5,2,4,4,4,3,4,5)
golfMatrix <- matrix(scores,nrow=9)
rownames(golfMatrix) <-c("Hole 1", "Hole 2", "Hole 3", "Hole 4", "Hole 5", 
                         "Hole 6", "Hole 7", "Hole 8", "Hole 9")
colnames(golfMatrix)<- c("Phil", "Tiger", "Vijay")
golfMatrix


golfSVD <- svd(golfMatrix, nu=nrow(golfMatrix), nv=ncol(golfMatrix))

# the singular values ($d)
# left and right singular vectors ($u, $v)
golfSVD 

#  first left and right singular values ($u, $v)
approxGolf <- golfSVD$u[,1] %*% t(golfSVD$v[ ,1]) * golfSVD$d[1]

approxGolf

#  first two singlar values ??
golfSVD$u[,1:2] %*% diag(golfSVD$d[1:2]) %*% t(golfSVD$v[ ,1:2])

```









