---
title: "Graph"
output: html_document
---

# Operations

## igraph 

```r
# get 
E(g) # edges
V(g) # vertices

get.edgelist(g)  # all edges from to

# delete 
g <- delete.edges(g, which(E(g)$weight<=0.1) ) 
g <- delete.vertices(g, which(degree(g)<1) )

# keep specified vertices and all the edges between
g2 <- induced_subgraph(g, 1:7)

# calculates the length of all the shortest paths from or to the vertices
shortest.paths()

```

# DAG
```{r, warning=F, message=F}
library(igraph)
g <- graph.tree(10)
plot(g)
is.dag(g) # Ture
g2 <- g + edge(5,1)
plot(g2)
is.dag(g2) # False
```

# Clique
Find cliques (complete subgraphs of an undirected graph)
```{r, warning=F}
library(igraph)
g <- graph.famous("bull")
cliques(g) # list of cliques       
sapply(cliques(g), length) # clique sizes
largest_cliques(g) # cliques with max number of 

# plot cliques
vcol <- rep("grey80", vcount(g))
vcol[unlist(largest_cliques(g))] <- "gold"
plot(as.undirected(g), vertex.label=V(g)$name, vertex.color=vcol)
```

# Centrality 
```r
g2 <- make_star(10)
V(g2)$label <- 1:10
g2 <- g2 - edge(6)
g2 <- as.undirected(g2)
E(g2)$weight <- 1:8 
E(g2)$label <- 1:8
plot(g2)
closeness(g2) # Inverse of the average length of the shortest paths to/from all the other vertices; more weight less closeness
1/closeness(g2,7)/9 # the auto assigned weight of disconnected node (7) to the rest of 9 nodes
```

# Community detection
```{r}
g <- graph.famous("Walther")
ceb <- cluster_edge_betweenness(g) 
dendPlot(ceb, mode="hclust")
plot(ceb, g) 
```


# Plot

## igraph

```{r, warning=F, message=F}
library(igraph)
df <- data.frame(
  A=c("Dublin", "Cork", "Galway") , 
  B=c("Cork", "Galway", "Dublin"))

dfg <- graph.data.frame(d=df, directed=FALSE)

V(dfg)$color="red" # set vertex color
E(dfg)$color="blue" # set edge color

# igraph_options(plot.layout=layout_as_tree) # tree graph
plot(dfg, vertex.label=(dfg)$name)

# get the various disconnected components 
components(dfg)

```

tkplot(dfg)  # interactive plot

rglplot(dfg) # 3D plot


```{r, warning=F, message=F}
g <- make_ring(10)
V(g)$name <- c("a", "b", "c", "d", "e", "f", "g", "h", "i", "j")
# returns with a list of graphs. b's 2 neighbors
plot(make_ego_graph(g, 2, V(g)[V(g)$name=="b"])[[1]])

```


## visNetwork

https://cran.r-project.org/web/packages/visNetwork/vignettes/Introduction-to-visNetwork.html
```{r, warning=F, message=F}
require(visNetwork, quietly = TRUE)
vertexes <- data.frame(id = 1:3)
edges <- data.frame(from = c(1,1,2), to = c(1,3,3))
visNetwork(vertexes, edges)

```

 Render a visNetwork object from an igraph object
```{r, warning=F, message=F}
# Not run: 
require(igraph)
igraph_network <- graph.famous("Walther")

# get data and plot :
data <- toVisNetworkData(igraph_network)
visNetwork(nodes = data$nodes, edges = data$edges)
# or plot directly
# visIgraph(igraph_network)
```
